In [289]:
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [290]:
horse_data=pd.read_csv('C:\\Users\\SumiranGupta\\Downloads\\horses.csv')

In [291]:
horse_data

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,cool,reduced,NaN,more_3_sec,...,45.0,8.4,NaN,NaN,died,no,11300,0,0,no
1,yes,adult,534817,39.2,88.0,20.0,NaN,NaN,pale_cyanotic,less_3_sec,...,50.0,85.0,cloudy,2.0,euthanized,no,2208,0,0,no
2,no,adult,530334,38.3,40.0,24.0,normal,normal,pale_pink,less_3_sec,...,33.0,6.7,NaN,NaN,lived,no,0,0,0,yes
3,yes,young,5290409,39.1,164.0,84.0,cold,normal,dark_cyanotic,more_3_sec,...,48.0,7.2,serosanguious,5.3,died,yes,2208,0,0,yes
4,no,adult,530255,37.3,104.0,35.0,NaN,NaN,dark_cyanotic,more_3_sec,...,74.0,7.4,NaN,NaN,died,no,4300,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,yes,adult,533886,NaN,120.0,70.0,cold,NaN,pale_cyanotic,more_3_sec,...,55.0,65.0,NaN,NaN,euthanized,no,3205,0,0,no
295,no,adult,527702,37.2,72.0,24.0,cool,increased,pale_cyanotic,more_3_sec,...,44.0,NaN,serosanguious,3.3,euthanized,yes,2208,0,0,yes
296,yes,adult,529386,37.5,72.0,30.0,cold,reduced,pale_cyanotic,less_3_sec,...,60.0,6.8,NaN,NaN,died,yes,3205,0,0,no
297,yes,adult,530612,36.5,100.0,24.0,cool,reduced,pale_pink,less_3_sec,...,50.0,6.0,serosanguious,3.4,lived,yes,2208,0,0,yes
298,yes,adult,534618,37.2,40.0,20.0,NaN,NaN,NaN,NaN,...,36.0,62.0,clear,1.0,euthanized,no,6112,0,0,no

In [292]:
horse_data.info()
horse_data['outcome']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   surgery                299 non-null    object
 1   age                    299 non-null    object
 2   hospital_number        299 non-null    int64
 3   rectal_temp            239 non-null    float64
 4   pulse                  275 non-null    float64
 5   respiratory_rate       241 non-null    float64
 6   temp_of_extremities    243 non-null    object
 7   peripheral_pulse       230 non-null    object
 8   mucous_membrane        252 non-null    object
 9   capillary_refill_time  267 non-null    object
 10  pain                   244 non-null    object
 11  peristalsis            255 non-null    object
 12  abdominal_distention   243 non-null    object
 13  nasogastric_tube       195 non-null    object
 14  nasogastric_reflux     193 non-null    object
 15  nasogastric_reflux_ph  53 non-null     float64
 16  rectal_exam_feces      197 non-null    object
 17  abdomen                181 non-null    object
 18  packed_cell_volume     270 non-null    float64
 19  total_protein          266 non-null    float64
 20  abdomo_appearance      134 non-null    object
 21  abdomo_protein         101 non-null    float64
 22  outcome                299 non-null    object
 23  surgical_lesion        299 non-null    object
 24  lesion_1               299 non-null    int64
 25  lesion_2               299 non-null    int64
 26  lesion_3               299 non-null    int64
 27  cp_data                299 non-null    object
dtypes: float64(7), int64(4), object(17)
memory usage: 65.5+ KB

0            died
1      euthanized
2           lived
3            died
4            died
          ...
294    euthanized
295    euthanized
296          died
297         lived
298    euthanized
Name: outcome, Length: 299, dtype: object

In [293]:
horse_data.describe()

,hospital_number,rectal_temp,pulse,respiratory_rate,nasogastric_reflux_ph,packed_cell_volume,total_protein,abdomo_protein,lesion_1,lesion_2,lesion_3
count,2.990000e+02,239.000000,275.000000,241.000000,53.000000,270.000000,266.000000,101.000000,299.000000,299.000000,299.000000
mean,1.087733e+06,38.168619,72.000000,30.460581,4.707547,46.307407,24.274436,3.039604,3659.709030,90.528428,7.387960
std,1.532032e+06,0.733744,28.646219,17.666102,1.982311,10.436743,27.364194,1.967947,5408.472421,650.637139,127.749768
min,5.184760e+05,35.400000,30.000000,8.000000,1.000000,23.000000,3.300000,0.100000,0.000000,0.000000,0.000000
25%,5.289040e+05,37.800000,48.000000,18.000000,3.000000,38.000000,6.500000,2.000000,2111.500000,0.000000,0.000000
50%,5.303010e+05,38.200000,64.000000,25.000000,5.000000,45.000000,7.500000,2.300000,2322.000000,0.000000,0.000000
75%,5.347360e+05,38.500000,88.000000,36.000000,6.500000,52.000000,56.750000,3.900000,3209.000000,0.000000,0.000000
max,5.305629e+06,40.800000,184.000000,96.000000,7.500000,75.000000,89.000000,10.100000,41110.000000,7111.000000,2209.000000

In [294]:
def binary_encode(dataframe,columns,positives_are):
    dataframe=dataframe.copy()
    for col,positive_are in zip(columns,positives_are):
        dataframe[col]=dataframe[col].apply(lambda x : 1 if x==positive_are else 0)
    return dataframe    
def ordinal_encode(dataframe,columns,orderings):
    dataframe=dataframe.copy()
    for col,ordering in zip(columns,orderings):
        dataframe[col]=dataframe[col].apply(lambda x : ordering.index(x))
    return dataframe 
def onehot_encode(dataframe,columns,prefixes):
    dataframe=dataframe.copy()
    for col,prefix in zip(columns,prefixes):
        dummies=pd.get_dummies(dataframe[col],prefix=prefix)
        dataframe=pd.concat([dataframe,dummies],axis=1)
        dataframe=dataframe.drop(col,axis=1)
    return dataframe

In [295]:
# '''
def preprocessing(df):
    df = df.copy()
    
    # Categorize categorical features
    binary_columns  = [
        'surgery',
        'age',
        'surgical_lesion',
        'cp_data'
    ]
    positive_values = [
        'yes',
        'adult',
        'yes',
        'yes'
    ]
    
    ordinal_columns = [
        'temp_of_extremities',
        'peripheral_pulse',
        'capillary_refill_time',
        'pain',
        'peristalsis',
        'abdominal_distention',
        'nasogastric_tube',
        'nasogastric_reflux',
        'rectal_exam_feces'    
    ]
    orderings = [
        ['cold', 'cool', 'normal', 'warm'],
        ['absent', 'reduced', 'normal', 'increased'],
        ['less_3_sec', '3', 'more_3_sec'],
        ['alert', 'depressed', 'mild_pain', 'severe_pain', 'extreme_pain'],
        ['absent', 'hypomotile', 'normal', 'hypermotile'],
        ['none', 'slight', 'moderate', 'severe'],
        ['none', 'slight', 'significant'],
        ['none', 'less_1_liter', 'more_1_liter'],
        ['absent', 'decreased', 'normal', 'increased']
    ]
    
    nominal_columns = [
        'hospital_number',
        'mucous_membrane',
        'abdomen',
        'abdomo_appearance'
    ]
    prefixes = [
        'HN',
        'MM',
        'AB',
        'AA'
    ]
    
    # Fill missing values
    for column in df.columns:
        if column in df.select_dtypes('object').columns:
            if column not in nominal_columns:
                df[column] = df[column].fillna(df[column].mode()[0])
        else:
            df[column] = df[column].fillna(df[column].mean())
    
    # Encode categorical feature columns dataframe,columns,positives_are
    df = binary_encode(df, columns=binary_columns, positives_are=positive_values)
    df = ordinal_encode(df, columns= ordinal_columns, orderings=orderings)
    df = onehot_encode(df, columns= nominal_columns, prefixes=prefixes)
    
    # Encode labels
    label_mapping = {'lived': 0, 'died': 1, 'euthanized': 2}
    df['outcome'] = df['outcome'].replace(label_mapping)
    
    # Split df into X and y
    y = df['outcome'].copy()
    X = df.drop('outcome', axis=1).copy()
    
    # Scale X with a standard scaler
    scaler = StandardScaler()
    X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
    
    return X, y

In [296]:
X,y =preprocessing(horse_data)

In [297]:
{column: list(X[column].unique()) for column in X.select_dtypes('object').columns}

{}

In [298]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,random_state=123)

In [299]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

print("Decision Tree Accuracy: {:.2f}%".format(model.score(X_test, y_test) * 100))

Decision Tree Accuracy: 62.22%

In [300]:
ensemble_model = RandomForestClassifier()
ensemble_model.fit(X_train, y_train)

print("Random Forest Accuracy: {:.2f}%".format(ensemble_model.score(X_test, y_test) * 100))

Random Forest Accuracy: 73.33%